"""
Spotprofielen en riderprofiel.

DIT IS HET ENIGE BESTAND DAT JE NORMAAL AANPAST.
"""

RIDERS = {
    "samen": {
        "label": "Hester & Marina",
        "min_kn": 15,
        "max_kn": 28,
        "max_delta": 10,       # drempel voor het label "rustig"
        "needs_shallow": False,
    },
}

SPOTS = [
    {
        "name": "Strand Horst",
        "wf": "strand_horst",
        "lat": 52.3103,
        "lon": 5.5593,
        "dirs": [(200, 50)],
        "shallow": True,
        "tide": None,
        "drive_min": 40,
        "primary": True,
        "note": "Vlagerig door bebouwing; met noord in de wind het rustigst.",
    },
    {
        "name": "Muiderberg",
        "wf": "muiderberg",
        "lat": 52.3258,
        "lon": 5.1208,
        "dirs": [(315, 90)],
        "shallow": True,
        "tide": None,
        "drive_min": 35,
        "primary": True,
        "note": "Groot ondiep vlak deel, veel lesgebied.",
    },
    {
        "name": "Schellinkhout",
        "wf": "schellinkhout",
        "lat": 52.6180,
        "lon": 5.1250,
        "dirs": [(135, 270)],
        "shallow": True,
        "tide": None,
        "drive_min": 60,
        "primary": True,
        "note": "Ondiep Markermeer, gunstig bij zuidoost tot west.",
    },
    {
        "name": "Zandmotor (Kijkduin)",
        "wf": "kijkduin_den_haag",
        "lat": 52.0533,
        "lon": 4.1867,
        "dirs": [(180, 360)],
        "shallow": True,
        "tide": "SCHEVENINGEN",
        "sea": (52.0600, 4.1600),
        "drive_min": 55,
        "primary": True,
        "note": "Zee, maar ondiepe lagune bij de Zandmotor.",
    },
    {
        "name": "Brouwersdam meerzijde",
        "wf": "brouwersdam",
        "lat": 51.7580,
        "lon": 3.8560,
        "dirs": [(200, 290)],
        "shallow": True,
        "tide": None,
        "drive_min": 105,
        "primary": True,
        "note": "Vlakwater, ondiep tot ~100 m. Geen getij aan deze kant.",
    },
    {
        "name": "Wijk aan Zee",
        "wf": "wijk_aan_zee",
        "lat": 52.4700,
        "lon": 4.5700,
        "dirs": [(200, 360)],
        "shallow": False,
        "tide": "IJMUIDEN",
        "sea": (52.4750, 4.5400),
        "drive_min": 50,
        "primary": False,
        "note": "Water >2 m, staan kan niet: waterstart vereist. Alleen Zone 2.",
    },
    {
        "name": "Brouwersdam zeezijde",
        "wf": "brouwersdam",
        "lat": 51.7602,
        "lon": 3.8471,
        "dirs": [(200, 20)],
        "shallow": True,
        "tide": "BROUWERSHAVENSCHE GAT 08",
        "sea": (51.7700, 3.8200),
        "drive_min": 105,
        "primary": False,
        "note": "Alleen rond laagwater ondiep. Stroming bij opkomend water.",
    },
]
